# Generated by Django 5.1.4 on 2025-01-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='montadora',
            old_name='ano_funcacao',
            new_name='ano_fundacao',
        ),
    ]
