# Generated by Django 5.1.4 on 2025-01-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_modeloveiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeloveiculo',
            options={'ordering': ['montadora', 'nome'], 'verbose_name': 'Modelo de Veículo', 'verbose_name_plural': 'Modelos de Veículos'},
        ),
        migrations.AlterModelOptions(
            name='montadora',
            options={'ordering': ['nome'], 'verbose_name': 'Montadora', 'verbose_name_plural': 'Montadoras'},
        ),
        migrations.RenameField(
            model_name='modeloveiculo',
            old_name='motandora',
            new_name='montadora',
        ),
    ]
