# Generated by Django 5.1.4 on 2025-01-20 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='controller.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('equipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='controller.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('data_limite', models.DateField()),
                ('feito', models.BooleanField(default=False)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='controller.membro')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='controller.projeto')),
            ],
        ),
    ]
